local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
	s("codeforce", {
		t({
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"",
			"using ll = long long;",
			"using ld = long double;",
			"using vi = vector<int>;",
			"using vll = vector<long long>;",
			"using pii = pair<int, int>;",
			"using pll = pair<long long, long long>;",
			"",
			"#define sz(x) static_cast<int>((x).size())",
			"#define all(x) (x).begin(), (x).end()",
			"",
			"void __print(int x) { cerr << x; }",
			"void __print(long x) { cerr << x; }",
			"void __print(long long x) { cerr << x; }",
			"void __print(unsigned x) { cerr << x; }",
			"void __print(unsigned long x) { cerr << x; }",
			"void __print(unsigned long long x) { cerr << x; }",
			"void __print(float x) { cerr << x; }",
			"void __print(double x) { cerr << x; }",
			"void __print(long double x) { cerr << x; }",
			"void __print(char x) { cerr << '\\'' << x << '\\''; }",
			"void __print(const string &x) { cerr << '\\\"' << x << '\\\"'; }",
			"void __print(bool x) { cerr << (x ? \"true\" : \"false\"); }",
			"",
			"template<typename T, typename V>",
			"void __print(const pair<T, V> &x) { cerr << '{'; __print(x.first); cerr << \", \"; __print(x.second); cerr << '}'; }",
			"template<typename T>",
			"void __print(const T &x) { int f = 0; cerr << '{'; for (auto &i: x) { cerr << (f++ ? \", \" : \"\"); __print(i); } cerr << '}'; }",
			"void _print() { cerr << \"]\\n\"; }",
			"template <typename T, typename... V>",
			"void _print(T t, V... v) { __print(t); if (sizeof...(v)) cerr << \", \"; _print(v...); }",
			"",
			"#ifndef ONLINE_JUDGE",
			"#define debug(x...) cerr << \"[\" << #x << \"] = [\"; _print(x)",
			"#else",
			"#define debug(x...)",
			"#endif",
			"",
			"void solve() {",
			"  ",
		}),
		i(1, ""),
		t({
			"}",
			"",
			"int main() {",
			"  ios_base::sync_with_stdio(false);",
			"  cin.tie(nullptr);",
			"",
			"  cout << fixed << setprecision(12);",
			"",
			"  int t = 1;",
			"  if (cin >> t) {
			"    while (t--) {",
			"      solve();",
			"    }",
			"  }",
			"  return 0;",
			"}",
		}),
	}),
}
